### PR TITLE
Inline styles

### PR DESCRIPTION
**Pull request by motiz88**
Hey @sarink,

In my fork, I've changed the component's styling API to [purely use inline styles instead of CSS class names](http://blog.vjeux.com/2014/javascript/react-css-in-js-nationjs.html). This PR includes that change along with an updated README and corresponding demo code, but otherwise sticks to the way you've done things on this repo (module format, checking in `node_modules` etc). 

You will definitely need to indicate the breaking change via semver if you merge and publish this.

My fork may diverge further if I end up spending any more time on it: It will probably become CommonJS only, with a prepublish step handling ES6/7 and JSX. If you're interested I will keep maintaining easily-merged feature branches for my changes as long as that remains practical.

### CODE REVIEW

**Comment by sarink** [comment]
Hey @motiz88, do you think we could make so that either inline styles or classnames can be used? Maybe some sort of ``useInlineStyles`` prop, or even just checking if they've passed a ``className`` and if not falling back to the inline styles you've written? This way we don't break backwards-compatibility.

Also, right now the component supports all types of module formats, why would you only want to support CJS?

Lastly, I only checked in node_modules because I was lazy and didn't want to write a deploy script for the demo site (on the gh-pages branch). It likely will not be this way forever (hint hint, feel free to solve that problem ;)).

Anyway, what do you think?

**Comment by motiz88** [comment]
1) Keeping backwards compatibility does make sense. I'll see if I can get around to doing that.

2) Coding manually against multiple module formats violates DRY and is a maintenance pain. My usual approach is to code in ES6 (`import`, `export`) and transpile to CommonJS for npm using Babel. If any other module format is really needed (and I doubt that it is for new React projects, though I could be missing something) it can be just another build target.

**Comment by sarink** [comment]
In order to support other formats it's about 4 lines of JS at the top of the file. I think there's still a moderately-sized community that are using AMD or even just stand-alone script tags, and want to either use or experiment with React. Perhaps if this repo was incredibly complicated (and not literally just one file), I'd see your point.

I didn't feel the need for any sort of build system or compilation (YAGNI?), so I just wanted to keep it simple. I'm not opposed to these things, however, so if you're into it I totally welcome these efforts and would gladly merge them in! I would like to keep support for AMD and stand-alone window variables, though.

**Comment by sarink** [comment]
Hey man, how's this going?

**Pull request closed without merging**
