### PR TITLE
fix className for `targetAlwaysVisible: true` case

### PR DESCRIPTION
**Pull request by mgh**

### CODE REVIEW

**Comment by sarink** [comment]
Hey @mgh, can you explain your use case? This code was actually intentional; not a bug. The idea is that: normally the "target" is visible if you're dragging over the frame. But, if you set the `targetAlwaysVisible` prop, then it's always visible (so it's like simulating dragging over the frame, so it adds the "dragging-over-frame" class).

I can conceive how this may be a little awkward or confusing, but what do you suggest instead?

**Comment by mgh** [comment]
Hey @sarink, the use case is having the drop area always visible, but still having it change styles when something is dragged over the frame or target.  For example, you may want to show a current image with `<FileDrop></FileDrop>` and update the image styling as the user drags a new image over the window and drops it onto the current image.

I'd argue that having a class `file-drop-dragging-over-frame` always active is incorrect, since the name implies the file is currently dragging over the frame even when it isn't.

**Comment by sarink** [comment]
Well said. Merged. Thanks!

**Comment by sarink** [comment]
@mgh, I can republish the npm module tomorrow.

**Comment by mgh** [comment]
Awesome, thanks for the quick turnaround!

**Pull request merged**
