### PR TITLE
Custom Classnames

### PR DESCRIPTION
**Pull request by racingrebel**
In response to #35 .
Let me know what you think :smile: 
[I created a branch](https://github.com/racingrebel/react-file-drop/tree/custom-class-names-demo) with a modified demo that tests these changes.

### CODE REVIEW

**Comment by racingrebel** [comment]
@sarink Could you please review this PR when you get a chance :v:

**Comment by sarink** [comment]
✅ Tested and reviewed, this looks good except two lint errors:
```
ERROR: /react-file-drop/src/FileDrop/FileDrop.tsx[33, 66]: Missing trailing comma
ERROR: /react-file-drop/src/FileDrop/FileDrop.tsx[180, 7]: 'children' is declared but its value is never read.
```
Can you fix these quickly and push the changes?

After that, it's ready to be merged!

**Comment by racingrebel** [comment]
Oops, got them this time! No problem, let me know if there's anything else.

**Comment by sarink** [comment]
Published 0.2.7

**Pull request merged**
