### PR TITLE
Add react and react-dom ^17.0.0 as peer dependency

### PR DESCRIPTION
**Pull request by aclaes**
Hey :) We like to use this awesome lib with react 17 as peer dependency. Unfortunately there is an error on installation right now.

### CODE REVIEW

**Comment by vaunus** [comment]
This is also stopping us from using this package at the moment :(

**Comment by d526f861** [comment]
I'm also waiting on this update

**Comment by nathan-hellinga** [comment]
Waiting on this update. Can we get this merged?

**Comment by sarink** [comment]
Sorry about the delay on this!

**Pull request merged**
