### PR TITLE
Custom wrapper components

### PR DESCRIPTION
**Pull request by loopmode**
This allows users to specify `outerComponent` and `innerComponent` props. (default: `div`)

This allows usage in SVG, via `outerComponent="g"`.
The value can also be a render function or a component.

I have no experience with typescript, so I left the type as `:any` - I guess that should be improved. Otherwise it seems to work just fine.

Added an SVG example to the Demo.

### CODE REVIEW

**Comment by sarink** [comment]
Functionality that allowed this has been on my to-do list, thanks! It's going to be a few days before I can test and merge this, so if you require it immediately you might want to point at your own fork, and I'll get it wrapped up soon!

**Comment by loopmode** [comment]
Nah, it's all good - I do need it right away, but a nice side-effect of yarn workspaces is that we can keep a customized package in the local workspace until it gets published on npm.

**Comment by loopmode** [comment]
Didn't update readme/docs, wasn't sure how to actually format it. One way would be two headings/short sentences, one explainer for both:

##### outerComponent - String || function(props) (default: div)
Component or tag name for rendering the outer wrapper.

##### innerComponent - String || function(props) (default: div)
Component or tag name for rendering the inner wrapper. 

Supported types for ``outerComponent`` and ``innerComponent``:

- String - Any HTML or SVG tag name like ``div``, ``span``, ``g`` etc.
- Function - A render function or component class. Receives props and renders a react element.
    - props passed to ``outerComponent``: ``className, onDragOver, onDragLeave, onDrop``
    - props passed to ``innerComponent``: ``className``
    - example: component class: ``<FileDrop outerComponent={MyReactComponent}>``
    - example: render function: ``<FileDrop outerComponent={(props) => <span {...props} />} />``

**Comment by loopmode** [comment]
Ow crap. I messed up the PR by pushing with @loopmode namespace.

As you can see in https://github.com/sarink/react-file-drop/pull/33/commits/6711cac61a0feae9c405374d56da5c18df9be0a9, the actual changes were minimal.
Feel free to neglect this pull request and simply add the feature manually.

I have problems compiling within the yarn workspace, so I decided to publish it under my namespace for now.

**Comment by sarink** [comment]
Any chance of getting these conflicts fixed and having just the `inner/outerComponent` functionality?

**Pull request closed without merging**
